  version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      target: production
    container_name: fb-comment-frontend-prod
    ports:
      - "80:80"
    restart: always

  backend:
    build:
      context: ./backend
      target: production
    container_name: fb-comment-backend-prod
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=production
    restart: always
